[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "/opt/homebrew/bin/solc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
